#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r \
    0.org/p \
    0/

cp -r \
    0.org/U \
    0/

runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication decomposePar

runParallel snappyHexMesh -overwrite

runParallel checkMesh -writeFields '(nonOrthoAngle)' -constant

runParallel changeDictionary

runParallel $(getApplication)  #controldictのapplicationに書かれているソルバを実行

runApplication reconstructParMesh -constant

runApplication reconstructPar -latestTime
