#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication decomposePar

runParallel snappyHexMesh -overwrite

runParallel createPatch -overwrite

restore0Dir -processor

runParallel checkMesh -writeFields '(nonOrthoAngle)' -constant -allGeometry -allTopology

runParallel $(getApplication)  #controldictのapplicationに書かれているソルバを実行

runApplication reconstructParMesh -constant

runApplication reconstructPar -latestTime
